### ISSUE TITLE
is it worth hooking `.onerror` as well?

### ISSUE THREAD

**Issue by jokeyrhyme** [filamentgroup/loadJS#16]
We noticed a few cases where the `.onload` callback wasn't being called. Without investigating this too deeply, we noticed Chrome executes the `.onerror` method if there is one, when loading the script element fails.

**Comment by scottjehl** [comment]
Good question. Any idea of the browser support for that? I confess I've maybe never used it for a `script` element.

**Comment by jokeyrhyme** [comment]
Internet Explorer and Safari might be problematic:
- http://stackoverflow.com/questions/538745/how-to-tell-if-a-script-tag-failed-to-load
I'll test them later.

**Comment by jokeyrhyme** [comment]
With `onerror` hooked, I tried the following on scripts that were good, missing and had bad syntax:

```javascript
loadJS(url, function (e) {
  console.log(url, e.type);
});
```

In Chrome and Firefox on Linux, and Safari on iOS 8:
> - "good.js", "load"
> - "missing.js", "error"
> - "badsyntax.js", "load"

So modern Safari seems fine, as are the latest Chrome and Firefox. My IE VMs are nearly finished downloading, so I'll have more to report in a minute. :)

**Comment by jokeyrhyme** [comment]
Actually, I just went through the Require.js source code: https://github.com/jrburke/requirejs/blob/master/require.js
There are a few tricks to this if we were discussing comprehensive coverage of possible outcomes.

**Comment by scottjehl** [comment]
I think it's beyond the scope for this. Closing it out but thanks for the discussion!

**Comment by jokeyrhyme** [comment]
I ended up borrowing @jrburke's code in Require.JS and extracting it into a separate project: https://github.com/jokeyrhyme/loadjs-ex-requirejs
