### ISSUE TITLE
Asynchronously loading several JavaScript files

### ISSUE THREAD

**Issue by taliscope** [filamentgroup/loadJS#17]
@scottjehl @zachleat @jakeboone02 congratulations for your very great script.

However, allow me to submit this question:
Is it possible to adjust your code so that it could support simultaneous loading of multiple JavaScript files together.
if so, how?

Have a nice day, happy Easter and God bless

**Comment by scottjehl** [comment]
The goal of this script is to simply load a script asynchronously, but you may call it more than once to load multiple scripts if you need to. Ensuring that scripts execute in the order they're called involves workarounds that are beyond the scope here, so we don't intend to support it. You can check out some other scripts if you need that functionality, but we try to make different builds that combine the files necessary for making a single javascript request, when possible.

**Comment by taliscope** [comment]
@scottjehl THANKS very much for your fast reply
