### ISSUE TITLE
Support for AMD and Node?

### ISSUE THREAD

**Issue by teodragovic** [filamentgroup/loadJS#19]
Before making PR (https://github.com/teodragovic/loadJS/commit/3c12bc8b2f1800dbc386c8d1b2d6af89dae6d4f1) figured I'll ask here for thoughts about this.

Since it's already published on npm this addition would make possible to do stuff like `loadJS = require('fg-loadjs')` from inside Node env. without the need to c/p (event if it's just few lines of code).

**Comment by rayshan** [comment]
+1

**Comment by rayshan** [comment]
For webpack, this works as a workaround with exports loader:

```js
{
    test: /fg-loadjs/,
    loader: "exports",
    query: "loadJS"
}
```

Then you can `import loadJS from "fg-loadjs"`

**Comment by rayshan** [comment]
Thanks @scottjehl!
