### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by thasmo** [filamentgroup/loadJS#25]
I'd love to see a `bower.json` for easier setup via Bower.

**Comment by zachleat** [comment]
Sorry, we don’t support bower on our modules (and sorry for the late response)

**Comment by thasmo** [comment]
If you implement bower support today, I'd open an issue to ask for removal of bower support. :+1: :)

**Comment by zachleat** [comment]
Haha, love it! Thanks for the laugh @thasmo 😀

**Comment by davidpustai** [comment]
@zachleat Could you share the reason? I can do with npm just well, but is there a downside to support more "platforms"?

**Comment by thasmo** [comment]
@davidpustai Because bower is kind of [deprecated](https://bower.io/blog/).

**Comment by davidpustai** [comment]
@thasmo Thanks!
