### ISSUE TITLE
Are there any known issues for loadjs with IE10 on Windows 8

### ISSUE THREAD

**Issue by seanfoo** [filamentgroup/loadJS#27]
I'm having an issue with IE10 on Windows 8.  It doesn't appear like our js is being loaded and fired properly, but the console isn't throwing any errors.

This is proving a bear to debug.  When I run the firing code from the console, things appear to work, but is doesn't fire on a regular page load.  It may not be a loadjs issue, but I'm just trying to verify there aren't known issues.

Here is a sample page.
http://www.pro-football-reference.com/teams/nwe/2016.htm

we run everything using this in the header.

```
<script>
if (Modernizr.is_modern) { loadJS( "https://d2p3bygnnzw9w3.cloudfront.net/req/201611103/js/pfr/sr-min.js"     , function() { vjs_ready(sr_fire_js); }); }
else                     { loadJS( "https://d2p3bygnnzw9w3.cloudfront.net/req/201611103/js/pfr/sr-basic-min.js", function() { vjs_ready(sr_fire_js); }); }
</script>    
```

vjs_ready is just a simple script to run the function as parameter on doc.ready.

thank you.

**Comment by scottjehl** [comment]
@seanfoo sorry for the delay. Were you able to work this out? It sounds to us like it could be a domready function issue, as we've seen some domready functions have trouble reliably running when included in an async loaded file. 
To isolate that, have you made sure that you can simply run `function(){ console.log( "loaded" ); }`?

**Comment by scottjehl** [comment]
Closing as this doesn't seem to show up in production and the issue would otherwise need a reproducible demo to explore an edge case. Thanks!
